{% set name = "libswmm" %}
{% set version = "5.2.0.dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../
  git_tag: HEAD

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - cmake
    - gcc     # [unix]
    - python  # [win]
    - vc 9    # [win and py27]
    - vc 10   # [win and py34]
    - vc 14   # [win and py>=35]
  run:
    - libgcc  # [unix]
    - vc 9    # [win and py27]
    - vc 10   # [win and py34]
    - vc 14   # [win and py>=35]

test:
  commands:
    - run-swmm --help  
    - run-swmm --version

about:
  home: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model
  license_family: MIT
  license: MIT
  license_file: LICENSE.txt
  summary: ORD Stormwater Management Model (aka SWMM).
  description: |
    SWMM is a dynamic hydrology-hydraulic water quality simulation model.
    It is used for single event or long-term (continuous) simulation of
    runoff quantity and quality from primarily urban areas. SWMM source
    code is written in the C Programming Language and released in the
    Public Domain.
  dev_url: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model

extra:
  recipe-maintainers:
    - goanpeca
    - bemcdonnell
